import pandas as pd


def from_csv(filename):
    """
    Load SAP CRM Service Tickets from CSV file generated by exporting
    Service Tickets in the SAP CRM UI.

    Parameters
    ----------
    filename -- Unicode
        a filename of a CSV file
    """
    pass


def from_excel(filename):
    """
    Load SAP CRM Service Tickets from Excel file generated with SAP Analysis
    Excel Add-On.

    Parameters
    ----------
    filename -- Unicode
        a filename of an Excel file
    """
    pass
