from datetime import datetime as dt
import functools

import pandas as pd

from .utils import parse_kb, parse_itrack, strpname, strpgroup
from ...utils.recipes import when_empty, strpdate, itemgetter
from ...utils.pandas import categorize, busday_counter

PRIORITIES = ('Very high', 'High', 'Medium', 'Low')

strpprio = itemgetter(dict(zip(
    PRIORITIES,
    ['P{:d}'.format(i+1) for i, _ in enumerate(PRIORITIES)]
)), 'P2')

CSV_CONVERTERS = {
    'Service Order ID': int,
    'Employee Responsible Name': strpname,
    'Service Employee Grp': strpgroup,
    'Reported By Name': when_empty('Undefined'),
    'Follow-up Date': strpdate,
    'Changed On': strpdate,
    'Posting Date': strpdate,
    'Priority': strpprio,
    'Contact': strpname
}


@categorize(['User Status', 'Market', 'Service Employee Grp',
             'Employee Responsible Name', 'Reported By Name',
             'Phantom Ibase', 'FRT Owner', 'Priority', 'Contact',
             'iTrack'])
def from_csv(filename, sep='\t', encoding='utf-16-le'):
    """
    Load SAP CRM Service Tickets from CSV file generated by exporting
    Service Tickets in the SAP CRM UI.

    Parameters
    ----------
    filename -- Unicode
        a filename of a CSV file
    sep -- str, default '\t'
        Delimiter to use.
    encoding -- str, default 'utf-16-le'
        Encoding to use for UTF when reading/writing (ex. 'utf-8').
    """
    return (pd.read_csv(filename, sep=sep, encoding=encoding,
                       index_col=False, converters=CSV_CONVERTERS)
            .assign(
                iTrack=parse_itrack,
                KB=parse_kb,
                IsActive=lambda df: ~df['User Status'].isin(
                    ['Closed', 'Cancelled']
                ),
                Age=busday_counter('Posting Date', 'Closed On'),
                Idle=busday_counter('Changed On')
            ))


def from_excel(filename):
    """
    Load SAP CRM Service Tickets from Excel file generated with SAP Analysis
    Excel Add-On.

    Parameters
    ----------
    filename -- Unicode
        a filename of an Excel file
    """
    pass
